[Feature] Add support for HID Bootloader generation
qmk/lufa pull request #6
Opened 2019-09-20 07:15 UTC by drashna

This is from qmk_firmware#2479 which adds the ability to generate a HID Bootloader for boards.  

Additionally, this ports the pin mapping from config_common, so that it's more accurate and supports more boards.

2019-11-06 23:12 UTC, fauxpark commented on LUFA/Drivers/Board/AVR8/QMK/LEDs.h
> +#        define PIND_ADDRESS 0x9
LUFA doesn't support these MCUs. Might as well delete this block.

2019-12-29 06:54 UTC, fauxpark approved these changes
Okay, I finally got around to testing this, on a Pro Micro - speaker and LED work 👍 Toolbox doesn't know what to do with it, of course, it thinks it's a DFU device because of the VID, but that can easily be sorted out.

Small disappointing thing: because Windows gives this the `HidUsb` driver, the vendor and product strings don't show up. We'll need to get these strings using HidLibrary or something similar for the Windows toolbox.

Otherwise, LGTM 🎉

2019-12-29 23:13 UTC, fauxpark requested changes

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/BootloaderHID.c
> +	  USB_USBTask();			uint16_t keypress = 0;
```suggestion
	  USB_USBTask();
	  uint16_t keypress = 0;
```

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/BootloaderHID.c
> +        bool pressed = (PIN(QMK_ESC_INPUT) & NUM(QMK_ESC_INPUT));
```suggestion
		bool pressed = (PIN(QMK_ESC_INPUT) & NUM(QMK_ESC_INPUT));
```

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/BootloaderHID.c
> +    DDR(QMK_ESC_INPUT) |= NUM(QMK_ESC_INPUT);
Spaces to tabs

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/makefile
> +
```suggestion
```

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
> +
```suggestion
```

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
> +
```suggestion
```

2019-12-29 23:13 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
> +        }
et ici

2020-10-08 07:51 UTC, fauxpark requested changes

2020-10-08 07:51 UTC, fauxpark commented on Bootloaders/HID/BootloaderHID.c
> +    DDR(QMK_ESC_INPUT) |= NUM(QMK_ESC_INPUT);
```suggestion
	// output setup
	DDR(QMK_ESC_OUTPUT) |= NUM(QMK_ESC_OUTPUT);
	PORT(QMK_ESC_OUTPUT) |= NUM(QMK_ESC_OUTPUT);

	// input setup
	DDR(QMK_ESC_INPUT) |= NUM(QMK_ESC_INPUT);
```

2020-10-08 07:51 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
> +    #define PRODUCT Keyboard
```suggestion
	#define MANUFACTURER QMK
#endif
#ifndef PRODUCT
	#define PRODUCT Keyboard
```

2020-10-08 07:51 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
> +    }
```suggestion
	else if (DescriptorType == DTYPE_String) {
		if (DescriptorNumber == STRING_ID_Language)
		{
			Address = &LanguageString;
			Size    = LanguageString.Header.Size;
		}
		else if (DescriptorNumber == STRING_ID_Manufacturer)
		{
			Address = &ManufacturerString;
			Size    = ManufacturerString.Header.Size;
		}
		else if (DescriptorNumber == STRING_ID_Product)
		{
			Address = &ProductString;
			Size    = ProductString.Header.Size;
		}
	}
```

2020-10-08 07:51 UTC, fauxpark commented on Bootloaders/HID/Descriptors.c
>  }
```suggestion
}

```

2020-10-08 07:51 UTC, fauxpark commented on Bootloaders/HID/BootloaderHID.c
>  }
```suggestion
}

```

2021-07-01 01:29 UTC, fauxpark commented
Would like to get this in this breaking changes cycle.

2021-07-15 02:56 UTC, fauxpark commented
Conflict on gitignore now.

2021-07-15 03:10 UTC, drashna commented
Done.

2021-07-15 03:21 UTC, drashna commented
> Okay, I finally got around to testing this, on a Pro Micro - speaker and LED work 👍 Toolbox doesn't know what to do with it, of course, it thinks it's a DFU device because of the VID, but that can easily be sorted out.
> 
> Small disappointing thing: because Windows gives this the `HidUsb` driver, the vendor and product strings don't show up. We'll need to get these strings using HidLibrary or something similar for the Windows toolbox.

From the looks of it, it works exactly like the halfkay bootloader, just ... larger.  

There is included source for creating a version of teensy_loader_cli that supports both device types, but it's also outdated.  I have updated code, and ... may should add it here too.

2021-07-15 03:35 UTC, drashna commented
Also, done now. 

Additionally, it would be trivial to add a different VID/PID combo to the cli

2021-07-15 07:41 UTC, drashna commented
Hmm, this is compiling over 2kb for me.  I think it is supposed to come in under that.

The at90usb1286 config does come in under 4096 by a good margin, though.

2021-07-15 07:48 UTC, fauxpark commented on Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c
>  /* Teensy Loader, Command Line Interface
Think we could upstream this?

2021-07-15 07:48 UTC, fauxpark approved these changes

2021-07-15 07:50 UTC, fauxpark commented
> Hmm, this is compiling over 2kb for me. I think it is supposed to come in under that.

Nah, the boot section size in the makefile is set to 4kB. I think this would be the case for all of the LUFA bootloader, except of course the mass storage one.

2021-07-15 15:01 UTC, drashna commented on Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c
>  /* Teensy Loader, Command Line Interface
Yeah, I'll upstream it, as well.

2021-07-15 15:01 UTC, drashna commented
> > Hmm, this is compiling over 2kb for me. I think it is supposed to come in under that.
> 
> Nah, the boot section size in the makefile is set to 4kB. I think this would be the case for all of the LUFA bootloader, except of course the mass storage one.

Okay, wasn't entirely sure.

2021-07-16 18:15 UTC, drashna commented on Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c
>  /* Teensy Loader, Command Line Interface
Should I revert the changes for now?

2021-07-16 18:27 UTC, fauxpark commented on Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c
>  /* Teensy Loader, Command Line Interface
Yeah, probably.

2021-07-18 16:04 UTC, drashna commented on Bootloaders/HID/HostLoaderApp/hid_bootloader_cli.c
>  /* Teensy Loader, Command Line Interface
Removed.

2021-07-18 16:06 UTC, merged